version: '3.4'

services:
  server:
    image: server
    build:
      context: chat-app/server
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 9090:9090
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
